spring:
  profiles:
    active: dev
  mustache:
    servlet:
      expose-request-attributes: true
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: io.anichu.anichu.vo
server:
  servlet:
    encoding:
      force: true